import java.io.File
import java.nio.file.Paths

val tempDir: File = Paths.get(System.getProperty("user.dir")).toFile()


val alterSyllables = mapOf(
    "a" to "ei",
    "b" to "bi",
    "c" to "xi",
    "d" to "di",
    "e" to "yi",
    "f" to "ai fu",
    "g" to "ji",
    "h" to "ai chi",
    "i" to "ai",
    "j" to "zhei",
    "k" to "kai",
    "l" to "ai lu",
    "m" to "ai mu",
    "n" to "en",
    "o" to "ou",
    "p" to "pi",
    "q" to "kiu",
    "r" to "a",
    "s" to "ai si",
    "t" to "ti",
    "u" to "you",
    "v" to "wei",
    "w" to "da bu liu",
    "x" to "ai ke si",
    "y" to "wai",
    "z" to "zei",
    "." to "dian",
    "0" to "ling",
    "1" to "yi",
    "2" to "er",
    "3" to "san",
    "4" to "si",
    "5" to "wu",
    "6" to "liu",
    "7" to "qi",
    "8" to "ba",
    "9" to "jiu",
)
    .map { (k, v) -> k to v.split(" ") }
    .toMap()

val yuanShengDaDie = mapOf(
    "miyu" to listOf("米浴说的道理", "啊米浴说的道理"),
    "djha" to listOf("大家好啊", "大家好"),
    "wssddl" to listOf("我是说的道理"),
    "jtlaidian" to listOf("今天来点大家想看的东西", "今天来点儿大家想看的东西", "今天来点大家想看的东西啊"),
    "sddl" to listOf("说的道理"),
    "bobi" to listOf("波比是我爹", "啊嘛波比是我爹"),
    "aksa" to listOf("奥克苏恩"),
    "alaf" to listOf("奥利安费", "奥力安费"),
    "wsmy" to listOf("为什么耶", "为什么呀"),
    "anxu" to listOf("安修"),
    "ands" to listOf("欧内的手"),
    "hbx" to listOf("哈比下", "哈陛下", "哈比霞", "哈毙霞"),
    "hh" to listOf("好汉"),
    "hlldxf" to listOf("哈里路大旋风", "哈利路大旋风"),
    "wow" to listOf("哇袄", "哇奥", "沃袄"),
    "hj" to listOf("获嘉", "获加"),
    "jb" to listOf("击败", "鸡掰"),
    "xg" to listOf("炫狗"),
    "znhj" to listOf("尊尼获加"),
    "zn" to listOf("尊尼"),
    "yzd" to listOf("原子弹"),
    "alala" to listOf("奥利奥利安"),
    "cc" to listOf("冲刺"),
    "hm" to listOf("哈姆"),
    "wuzi" to listOf("乌兹"),
    "yyds" to listOf("永远的神"),
    "yts" to listOf("一坨屎", "一坨史", "一拖四", "一坨四", "依托史"),
    "ytszg" to listOf("一坨史这个"),
    "sfrs" to listOf("释放忍术"),
    "wsfrs" to listOf("我释放忍术"),
    "nmyyq" to listOf("纳米悠悠球"),
    "yfsszz" to listOf("影分身十字斩"),
    "xwyt" to listOf("吓我一跳我释放忍术"),
    "wxhn" to listOf("我喜欢你"),
    "nxhw" to listOf("你喜欢我"),
    "xhn" to listOf("喜欢你"),
    "xhw" to listOf("喜欢我"),
    "xh" to listOf("喜欢"),
    "fm" to listOf("凤鸣"),
    "yw" to listOf("一五"),
    "ahhhhh" to listOf("啊哈哈哈哈哈哈", "呵呵呵呵呵呵", "啊呵呵呵呵呵", "哈哈哈哈哈哈"),
    "kn" to listOf("凯南"),
    "kda" to listOf("开大啊"),
    "cnmkd" to listOf("草拟嘛开大"),
    "bzl" to listOf("憋追了", "憋追啦"),
    "wcsndm" to listOf("我草似你的马"),
    "wc" to listOf("我草", "我超"),
    "zbb" to listOf("猪鼻吧"),
    "zb" to listOf("猪鼻"),
    "zzmzmca" to listOf("这怎么这么菜啊"),
    "zzmzmc" to listOf("这怎么这么菜"),
    "dyndynjyxa" to listOf("队友呢队友呢救一下啊"),
    "dynjyxa" to listOf("队友呢救一下啊"),
    "dyndyn" to listOf("队友呢队友呢"),
    "dyn" to listOf("队友呢"),
    "llkla" to listOf("拉了胯了啊", "拉了胯了呀"),
    "llk" to listOf("拉了胯"),
    "dhdjbtmd" to listOf("大伙都几把挺猛的", "大伙都挺猛的"),
    "dnzkzmj" to listOf("到你这块怎么就", "怎么到你这块就", "到你这块就"),
    "dydzwwjjdnmblp" to listOf("打野的走位我就觉得你麻痹离谱", "打野的走位我就觉得离谱"),
    "lp" to listOf("离谱"),
    "nmblp" to listOf("你麻痹离谱"),
    "nltmxzsnnbslgsmwye" to listOf("你老他妈想着刷你那逼三狼干什么玩意儿", "你老他妈想着刷你那逼三狼干什么玩意啊", "你老他妈想着刷你那逼三狼干什么玩意儿啊"),
    "nltmxzsnnbsl" to listOf("你老他妈想着刷你那逼三狼"),
    "bsl" to listOf("逼三狼"),
    "ybmr" to listOf("一把米若", "一把米诺"),
    "oxgoxg" to listOf("欧西给欧西给"),
    "oxg" to listOf("欧西给"),
    "aymn" to listOf("哎呀米诺", "哎呀米若", "啊呀米诺"),
    "ah" to listOf("啊哈"),
    "ml" to listOf("没了", "没啦"),
    "rq" to listOf("rq"),
    "amns" to listOf("啊米诺斯", "啊米若斯", "哈米诺斯", "哈米诺"),
    "padorupadoru" to listOf("padorupadoru"),
    "padoru" to listOf("padoru"),
    "hjm" to listOf("哈基米"),
    "fengmi" to listOf("蜂蜜"),
    "nwqdzg" to listOf("那我缺的这个"),
    "zgyyzykd" to listOf("这个营养这一块的", "这个营养这一块"),
    "yyzykd" to listOf("营养这一块的", "营养这一块"),
    "zykd" to listOf("这一块的", "这一块"),
    "sgwba" to listOf("谁给我补啊"),
    "bbd" to listOf("饱饱的"),
    "jchz" to listOf("韭菜盒子"),
    "cjbgj" to listOf("臭几把杠精"),
    "ngwshl" to listOf("你给我说话来", "你给我说话"),
    "gj" to listOf("杠精"),
    "dfg" to listOf("低分狗"),
    "tg" to listOf("抬杠"),
    "hz" to listOf("患者"),
    "nbyjdswdg" to listOf("你白银觉得是我的锅"),
    "njswdg" to listOf("那就是我的锅"),
    "wsmnzdm" to listOf("为什么你知道吗"),
    "ywbysdh" to listOf("因为白银说的话"),
    "jxsyg" to listOf("就像是一个"),
    "azwq" to listOf("癌症晚期"),
    "sdhyy" to listOf("说的话一样"),
    "tdyjzyl" to listOf("他都已经这样了"),
    "nwsmbsct" to listOf("你为什么不顺从他"),
    "nzygr" to listOf("你总要给人"),
    "zhydsj" to listOf("最后一段时间"),
    "yghdhyb" to listOf("一个好的回忆吧", "一个好的回忆"),
    "zhdsgl" to listOf("最后的时光里", "最后的时光了", "最后的时光"),
    "byzg" to listOf("白银这个"),
    "byhj" to listOf("白银黄金"),
    "zwsyd" to listOf("再往上一点儿", "再往上一点"),
    "bjzs" to listOf("白金钻石"),
    "kns" to listOf("可能说"),
    "aydsl" to listOf("哎有点实力", "诶有点实力"),
    "nczyx" to listOf("能操作一下"),
    "bywx" to listOf("白银往下"),
    "ydw" to listOf("一到五"),
    "arjs" to listOf("啊人家是"),
    "rjs" to listOf("人家是"),
    "cswyxd" to listOf("纯属玩游戏的"),
    "wyx" to listOf("玩游戏"),
    "ywtljl" to listOf("因为太垃圾了"),
    "tljl" to listOf("太垃圾了"),
    "zjyzdzj" to listOf("自己也知道自己"),
    "msmsl" to listOf("没什么实力"),
    "sbqxbld" to listOf("上不去下不来的"),
    "sbqxbl" to listOf("上不去下不来"),
    "zgdw" to listOf("这个段位"),
    "htdr" to listOf("黄铜的人"),
    "htszljd" to listOf("黄铜是最垃圾的"),
    "zljd" to listOf("最垃圾的"),
    "txsq" to listOf("他想上去"),
    "tysbq" to listOf("他又上不去"),
    "zgfdszggd" to listOf("这个分段是最尴尬的"),
    "kzzll" to listOf("卡在这里了"),
    "yczbql" to listOf("又操作不起来"),
    "dxqb" to listOf("掉下去吧"),
    "tyjd" to listOf("他又觉得"),
    "bzd" to listOf("不值得"),
    "whbrychtdd" to listOf("我好不容易从黄铜打到"),
    "ddbyl" to listOf("打到白银了"),
    "byl" to listOf("白银了"),
    "wwsmhydxqn" to listOf("我为什么还要掉下去呢"),
    "yyg" to listOf("优越狗"),
    "wzm" to listOf("我最猛"),
    "wsmxzhbq" to listOf("为什么现在还不q"),
    "wsmbq" to listOf("为什么不q"),
    "aq" to listOf("aq"),
    "qddbrdea" to listOf("q打断别人的e啊"),
    "jxs" to listOf("就像是"),
    "wdg" to listOf("我的锅"),
    "dsn" to listOf("但是呢"),
    "tby" to listOf("他白银"),
    "tjd" to listOf("他觉得"),
    "yqw" to listOf("一起玩"),
    "mbf" to listOf("没办法"),
    "xcz" to listOf("想操作"),
    "hgg" to listOf("很尴尬"),
    "by" to listOf("白银"),
    "ht" to listOf("黄铜"),
    "huangjin" to listOf("黄金"),
    "yinwei" to listOf("因为"),
    "dw" to listOf("段位"),
    "sy" to listOf("所以"),
    "jd" to listOf("觉得"),
    "gg" to listOf("尴尬"),
    "bp" to listOf("不配"),
    "gt" to listOf("跟他"),
    "yq" to listOf("一起"),
    "sb" to listOf("是吧"),
    "wsm" to listOf("为什么"),
)
    .flatMap { (ysddFileName, aliasList) ->
        aliasList.map { alias ->
            alias to ysddFileName
        }
    }
    .sortedByDescending { it.first.length }
    .toMap()
